### ISSUE TITLE
error in extractPublicKeyFromCertificateSync

### ISSUE THREAD

**Issue by biancode** [node-opcua/node-opcua-crypto#1]
Dear Etienne,

I got an error on every connect and I can not find the problem on crypto_utils.js line 455 for me:
keyPem = exports.extractPublicKeyFromCertificateSync(certificate);
Please, I need some help to find out the problem.

```
  opcuaIIoT:server Server endpointUrl: opc.tcp://DevMountain.local:55388/UA/NodeREDIIOTServer securityMode: NONE securityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None +1s
  opcuaIIoT:server Server endpointUrl: opc.tcp://DevMountain.local:55388/UA/NodeREDIIOTServer securityMode: SIGN securityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic128 +0ms
  opcuaIIoT:server Server endpointUrl: opc.tcp://DevMountain.local:55388/UA/NodeREDIIOTServer securityMode: SIGN securityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15 +0ms
  opcuaIIoT:server Server endpointUrl: opc.tcp://DevMountain.local:55388/UA/NodeREDIIOTServer securityMode: SIGN securityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic192 +0ms
  opcuaIIoT:server Server endpointUrl: opc.tcp://DevMountain.local:55388/UA/NodeREDIIOTServer securityMode: SIGN securityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic192Rsa15 +1ms
  opcuaIIoT:server Server endpointUrl: opc.tcp://DevMountain.local:55388/UA/NodeREDIIOTServer securityMode: SIGN securityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic256 +0ms
  opcuaIIoT:server Server endpointUrl: opc.tcp://DevMountain.local:55388/UA/NodeREDIIOTServer securityMode: SIGN securityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic256Rsa15 +0ms
  opcuaIIoT:server Server endpointUrl: opc.tcp://DevMountain.local:55388/UA/NodeREDIIOTServer securityMode: SIGN securityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256 +0ms
  opcuaIIoT:server Server endpointUrl: opc.tcp://DevMountain.local:55388/UA/NodeREDIIOTServer securityMode: SIGNANDENCRYPT securityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic128 +0ms
  opcuaIIoT:server Server endpointUrl: opc.tcp://DevMountain.local:55388/UA/NodeREDIIOTServer securityMode: SIGNANDENCRYPT securityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15 +0ms
  opcuaIIoT:server Server endpointUrl: opc.tcp://DevMountain.local:55388/UA/NodeREDIIOTServer securityMode: SIGNANDENCRYPT securityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic192 +0ms
  opcuaIIoT:server Server endpointUrl: opc.tcp://DevMountain.local:55388/UA/NodeREDIIOTServer securityMode: SIGNANDENCRYPT securityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic192Rsa15 +0ms
  opcuaIIoT:server Server endpointUrl: opc.tcp://DevMountain.local:55388/UA/NodeREDIIOTServer securityMode: SIGNANDENCRYPT securityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic256 +0ms
  opcuaIIoT:server Server endpointUrl: opc.tcp://DevMountain.local:55388/UA/NodeREDIIOTServer securityMode: SIGNANDENCRYPT securityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic256Rsa15 +0ms
  opcuaIIoT:server Server endpointUrl: opc.tcp://DevMountain.local:55388/UA/NodeREDIIOTServer securityMode: SIGNANDENCRYPT securityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256 +0ms
  opcuaIIoT:server Primary Server Endpoint URL opc.tcp://DevMountain.local:55388/UA/NodeREDIIOTServer +0ms
  opcuaIIoT:server Server Initialized +1ms
 Setting debug for  server_tcp_transport            to  false
  opcuaIIoT:server Client connected new channel with address =  ::ffff:127.0.0.1  port =  61438 +6s
  opcuaIIoT:server Client connected with address = ::ffff:127.0.0.1 port = 61438 +0ms
  opcuaIIoT:server Client disconnected close channel with address =  ::ffff:127.0.0.1  port =  61438 +50ms
  opcuaIIoT:server Client disconnected with address = ::ffff:127.0.0.1 port = 61438 +1ms
<Buffer 30 82 03 02 30 82 02 6b a0 03 02 01 02 02 02 10 01 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 28 31 12 30 10 06 03 55 04 0a 13 09 4e 6f 64 65 4f ... >
00000000: 30 82 03 02 30 82 02 6b a0 03 02 01 02 02 02 10 01 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00    0...0..k.........0...*.H.w......
00000020: 30 28 31 12 30 10 06 03 55 04 0a 13 09 4e 6f 64 65 4f 50 43 55 41 31 12 30 10 06 03 55 04 03 13    0(1.0...U....NodeOPCUA1.0...U...
00000040: 09 4e 6f 64 65 4f 50 43 55 41 30 22 18 0f 32 30 31 37 30 35 31 37 31 34 35 37 32 36 5a 18 0f 32    .NodeOPCUA0"..20170517145726Z..2
00000060: 30 31 38 30 35 31 37 31 34 35 37 32 36 5a 30 28 31 12 30 10 06 03 55 04 0a 13 09 4e 6f 64 65 4f    0180517145726Z0(1.0...U....NodeO
00000080: 50 43 55 41 31 12 30 10 06 03 55 04 03 13 09 4e 6f 64 65 4f 50 43 55 41 30 81 9f 30 0d 06 09 2a    PCUA1.0...U....NodeOPCUA0..0...*
000000a0: 86 48 86 f7 0d 01 01 01 05 00 03 81 8d 00 30 81 89 02 81 81 00 dd 4e 1e df c0 ec cd cf 66 df a9    .H.w..........0......]N._@lMOf_)
000000c0: 69 2a 58 99 7a 9f c4 a4 00 59 06 2d 76 4c 4a e0 b9 84 77 e6 15 8c d9 db df 75 4b 65 53 5e 34 0a    i*X.z.D$.Y.-vLJ`9.wf..Y[_uKeS^4.
000000e0: 74 26 6c ca 99 8c e8 24 bd 3f 7d b8 e3 dd 87 a0 81 52 32 22 bc 29 11 8a 8d c9 cc d8 3f fc 72 8c    t&lJ..h$=?}8c]...R2"<)...ILX?|r.
00000100: 88 63 76 bf 21 97 63 b5 ab 6d 58 12 e9 16 68 9e db 20 ec f1 c8 06 b1 aa 69 fb a2 a7 4d 5b c8 c3    .cv?!.c5+mX.i.h.[.lqH.1*i{"'M[HC
00000120: f7 f9 c9 b4 69 89 51 d1 d9 a0 7d b2 e9 25 18 8b 0a 1e 02 ae 19 02 03 01 00 01 a3 82 01 35 30 82    wyI4i.QQY.}2i%............#..50.
00000140: 01 31 30 0c 06 03 55 1d 13 01 01 ff 04 02 30 00 30 1d 06 03 55 1d 0e 04 16 04 14 46 a0 4b 33 4e    .10...U.......0.0...U......F.K3N
00000160: ec fc ad d4 68 97 a7 75 47 e4 81 a9 16 f6 41 30 51 06 03 55 1d 23 04 4a 30 48 80 14 46 a0 4b 33    l|-Th.'uGd.).vA0Q..U.#.J0H..F.K3
00000180: 4e ec fc ad d4 68 97 a7 75 47 e4 81 a9 16 f6 41 a1 2c a4 2a 30 28 31 12 30 10 06 03 55 04 0a 13    Nl|-Th.'uGd.).vA!,$*0(1.0...U...
000001a0: 09 4e 6f 64 65 4f 50 43 55 41 31 12 30 10 06 03 55 04 03 13 09 4e 6f 64 65 4f 50 43 55 41 82 02    .NodeOPCUA1.0...U....NodeOPCUA..
000001c0: 10 01 30 4f 06 03 55 1d 11 04 48 30 46 86 26 75 72 6e 3a 44 65 76 4d 6f 75 6e 74 61 69 6e 2e 6c    ..0O..U...H0F.&urn:DevMountain.l
000001e0: 6f 63 61 6c 3a 4e 6f 64 65 4f 50 43 55 41 2d 43 6c 69 65 6e 74 82 09 6c 6f 63 61 6c 68 6f 73 74    ocal:NodeOPCUA-Client..localhost
00000200: 82 11 44 65 76 4d 6f 75 6e 74 61 69 6e 2e 6c 6f 63 61 6c 30 2c 06 09 60 86 48 01 86 f8 42 01 0d    ..DevMountain.local0,..`.H..xB..
00000220: 04 1f 16 1d 4f 70 65 6e 53 53 4c 20 47 65 6e 65 72 61 74 65 64 20 43 65 72 74 69 66 69 63 61 74    ....OpenSSL.Generated.Certificat
00000240: 65 30 0e 06 03 55 1d 0f 01 01 ff 04 04 03 02 02 fc 30 20 06 03 55 1d 25 01 01 ff 04 16 30 14 06    e0...U..........|0...U.%.....0..
00000260: 08 2b 06 01 05 05 07 03 01 06 08 2b 06 01 05 05 07 03 02 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b    .+.........+.......0...*.H.w....
00000280: 05 00 03 81 81 00 9d da 2d af 3d a8 da c0 dd 38 84 2c 92 ff d9 7c b8 0e 2f 2a 64 2c 06 ae 0e c8    .......Z-/=(Z@]8.,..Y|8./*d,...H
000002a0: 3e 0e 1e 46 fb 3a d8 97 7f cc ca 10 f0 6c 08 4f 79 48 55 60 00 e1 e4 12 b0 56 f3 ea fc ab b9 5a    >..F{:X..LJ.pl.OyHU`.ad.0Vsj|+9Z
000002c0: 6b 24 bf 0c 86 11 da c8 79 2a fe e4 b2 34 f6 2c f2 09 14 e1 f1 ab af ca 8e d3 45 a5 d1 79 12 43    k$?...ZHy*~d24v,r..aq+/J.SE%Qy.C
000002e0: f2 d0 60 73 1b 04 c2 7d 47 e9 54 cb 6a 07 96 85 88 11 cb 63 6e f3 1e e5 5f 97 b9 5e ef ea 3c ba    rP`s..B}GiTKj.....Kcns.e_.9^oj<:
00000300: 71 f9 1b 58 1f c2                                                                                  qy.X.B

18 May 18:29:23 - [red] Uncaught Exception:
18 May 18:29:23 - AssertionError: this.plainBlockSize === 0
    at new ChunkManager (.npm-global/lib/node_modules/node-red-iiot-opcua/node_modules/node-opcua/lib/misc/chunk_manager.js:120:9)
    at new SecureMessageChunkManager (.npm-global/lib/node_modules/node-red-iiot-opcua/node_modules/node-opcua/lib/misc/secure_message_chunk_manager.js:109:25)
    at MessageChunker.chunkSecureMessage (.npm-global/lib/node_modules/node-red-iiot-opcua/node_modules/node-opcua/lib/misc/message_chunker.js:85:26)
    at ServerSecureChannelLayer.send_response (.npm-global/lib/node_modules/node-red-iiot-opcua/node_modules/node-opcua/lib/server/server_secure_channel_layer.js:599:25)
    at ServerSecureChannelLayer._handle_OpenSecureChannelRequest (.npm-global/lib/node_modules/node-red-iiot-opcua/node_modules/node-opcua/lib/server/server_secure_channel_layer.js:828:10)
    at .npm-global/lib/node_modules/node-red-iiot-opcua/node_modules/node-opcua/lib/server/server_secure_channel_layer.js:1152:42
    at .npm-global/lib/node_modules/node-red-iiot-opcua/node_modules/node-opcua/lib/server/server_secure_channel_layer.js:668:13
    at Immediate.<anonymous> (.npm-global/lib/node_modules/node-red-iiot-opcua/node_modules/node-opcua-crypto/lib/crypto_utils.js:464:9)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by biancode** [comment]
that is the other side (client)

```
opcua-commander $ node index.js  -e opc.tcp://localhost:55388 -P=Basic256 -s=SIGN
AssertionError: self._secureChannel
    at OPCUAClient._createSession (/opcua-commander/node_modules/node-opcua/lib/client/opcua_client.js:158:5)
    at OPCUAClient.createSession (/opcua-commander/node_modules/node-opcua/lib/client/opcua_client.js:584:10)
    at /opcua-commander/index.js:127:12
    at Timeout.delayer [as _onTimeout] (/opcua-commander/node_modules/delayed/delayed.js:27:10)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by biancode** [comment]
found the problem - if it is in a private package it does not work -- @privateName/node-opcua-using-package

**Comment by biancode** [comment]
Please, can you fix that problem so that node-opcua is usable in private NPM's too?

**Comment by biancode** [comment]
at the end it works - my PC is broken and apparent corrupt now - I've to buy new hardware
